package com.previred.ejercicio.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DatabaseUtil {
    private static final Logger logger = LoggerFactory.getLogger(DatabaseUtil.class);
    private static Connection connection;

    static {
        try {
            Class.forName("org.h2.Driver"); // Carga el driver
        } catch (ClassNotFoundException e) {
            logger.error("Driver H2 no encontrado: ", e);
            throw new RuntimeException(e);
        }
    }

    public static Connection getConnection() throws SQLException {
        if (connection == null || connection.isClosed()) {
            connection = DriverManager.getConnection(
                    "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1",
                    "sa",
                    ""
            );
            initializeDatabase();
        }
        return connection;
    }

    private static void initializeDatabase() {
        try (Statement stmt = connection.createStatement()) {
            String sql = "CREATE TABLE empleados (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "nombre VARCHAR(255), " +
                    "apellido VARCHAR(255), " +
                    "rut VARCHAR(12) UNIQUE, " +
                    "cargo VARCHAR(255), " +
                    "salario_base DECIMAL(10,2), " +
                    "bonos DECIMAL(10,2), " +
                    "descuentos DECIMAL(10,2), " +
                    "salario_final DECIMAL(10,2)" +
                    ")";
            stmt.execute(sql);
            logger.info("Tabla 'empleados' creada exitosamente");
        } catch (SQLException e) {
            logger.error("Error al inicializar la BD: ", e);
        }
    }
}